# These are supported funding model platforms for xyz-rainbow

github: [xyz-rainbow] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
buy_me_a_coffee: xyzclouds # Replace with a single Buy Me a Coffee username
ko_fi: xyzclouds # Replace with a single Ko-fi username
patreon: xyzclouds # Replace with a single Patreon username
custom: ['https://paypal.me/rainbowkolors'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
